SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

CREATE TABLE items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL
);

INSERT INTO items (name) VALUES ('Пример 1'), ('Пример 2');
